iped-queue:
  image: setecrs/ipedqueue
  net: host
  volumes:
    - ./config/production.json:/root/ipedqueue/config/production.json
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - iped-volumes
  environment:
    - DEBUG=ipedqueue:*
  command: npm start
iped-volumes:
  image: setecrs/iped-config
  container_name: iped-volumes
  volumes:
    - /mnt/cloud/kff:/var/lib/kff:Z
    - /mnt/cloud/led:/var/lib/led:Z
    - /mnt/cloud/operacoes:/operacoes/:Z
  command: /bin/true
