redis:
  image: redis
  container_name: redis-test
  ports:
    - 127.0.0.1:6379:6379
  restart: on-failure
mongo:
  image: mongo
  container_name: mongo-test
  ports:
    - 127.0.0.1:27017:27017
  restart: on-failure
